name: "CS229_project"
channels:
  - pytorch
  - defaults
dependencies:
  - pytorch
  - numpy
  - scipy
  - tqdm
  - docopt
  - nltk
  - torchvision
  - pandas
  - xlrd
  - window-slider
  - pip
  - pip:
    - sentencepiece
    - sacrebleu
    - tensorboard
    - prophet
    - spacy
    - pytextrank
    - argparse
    - transformers
    - SentencePiece
    - datasets
    - rouge-score
    - transformers
    - ray